version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: shopeasy_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopeasy
      MYSQL_USER: shopeasy_user
      MYSQL_PASSWORD: shopeasy_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
